-- ============================================================
-- V1: CREACIÓN DEL ESQUEMA
-- Flyway ejecuta este script UNA sola vez (lo registra en
-- flyway_schema_history). Si ya se ejecutó, no vuelve a correr.
--
-- El esquema debe coincidir EXACTAMENTE con lo que esperan las
-- entidades JPA (ClaimEntity, ClaimHistoryEntity, UserEntity),
-- porque spring.jpa.hibernate.ddl-auto=validate las compara al arrancar.
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- Tabla USERS (módulo user)
--   - id: autogenerado (identity)
--   - email: único (exigido por @Column(unique=true))
--   - role: CHECK limita a los 3 roles del enum EnumRole
-- ────────────────────────────────────────────────────────────
CREATE TABLE users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    role  VARCHAR(20)  NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('CUSTOMER', 'SUPPORT', 'FINANCE'))
);

-- ────────────────────────────────────────────────────────────
-- Tabla CLAIMS (módulo claim)
--   - user_id: FK → users(id)
--   - status: CHECK limita a los estados del enum EnumStatus
--   - created_at: la llena Hibernate con @CreationTimestamp
-- ────────────────────────────────────────────────────────────
CREATE TABLE claims (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT,
    description VARCHAR(255) NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    user_id     BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_claims_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT claims_status_check CHECK (status IN
        ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REFUNDED'))
);

-- ────────────────────────────────────────────────────────────
-- Tabla CLAIM_HISTORY (trazabilidad / auditoría)
--   - claim_id: FK → claims(id)
--   - changed_by_user: FK → users(id)
--   - previous_status: NULLABLE (primera transición puede no tener anterior)
--   - changed_at: la llena Hibernate con @CreationTimestamp
-- ────────────────────────────────────────────────────────────
CREATE TABLE claim_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id         BIGINT       NOT NULL,
    previous_status  VARCHAR(20),
    new_status       VARCHAR(20)  NOT NULL,
    changed_by_user  BIGINT       NOT NULL,
    changed_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_history_claim FOREIGN KEY (claim_id) REFERENCES claims (id),
    CONSTRAINT fk_history_user  FOREIGN KEY (changed_by_user) REFERENCES users (id),
    CONSTRAINT claim_history_new_status_check CHECK (new_status IN
        ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REFUNDED')),
    CONSTRAINT claim_history_previous_status_check CHECK (previous_status IN
        ('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REFUNDED'))
);
